global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'load-balancer'
    # 'lb' is the load balancer service in docker-compose. If you instead run the
    # balancer on the host, change this to 'host.docker.internal:8080'.
    static_configs:
      - targets: ['lb:8080']
    scrape_interval: 5s
    metrics_path: /metrics